import faceTest from "./faceTest.png";

let workers = [
  {src:faceTest, name:"Betty", id:1},
    {src:faceTest, name:"Brian", id:2},
    {src:faceTest, name:"Josie", id:3},
    {src:faceTest, name:"Betty", id:4},
    {src:faceTest, name:"Brian", id:5},
    {src:faceTest, name:"Josie", id:6},
    {src:faceTest, name:"Betty", id:7},
    {src:faceTest, name:"Brian", id:8},
    {src:faceTest, name:"Josie", id:9},
    {src:faceTest, name:"Betty", id:10},
    {src:faceTest, name:"Brian", id:11},
    {src:faceTest, name:"Josie", id:12},
    {src:faceTest, name:"Betty", id:13},
    {src:faceTest, name:"Brian", id:14},
    {src:faceTest, name:"Josie", id:15},
    {src:faceTest, name:"Betty", id:16},
    {src:faceTest, name:"Brian", id:17},
    {src:faceTest, name:"Josie", id:18},
    {src:faceTest, name:"Betty", id:19},
    {src:faceTest, name:"Brian", id:20},
    {src:faceTest, name:"Josie", id:21},
    {src:faceTest, name:"Betty", id:22},
    {src:faceTest, name:"Brian", id:23},
    {src:faceTest, name:"Josie", id:24},
    {src:faceTest, name:"Betty", id:1},
    {src:faceTest, name:"Brian", id:2},
    {src:faceTest, name:"Josie", id:3},
    {src:faceTest, name:"Betty", id:4},
    {src:faceTest, name:"Brian", id:5},
    {src:faceTest, name:"Josie", id:6},
    {src:faceTest, name:"Betty", id:7},
    {src:faceTest, name:"Brian", id:8},
    {src:faceTest, name:"Josie", id:9},
    {src:faceTest, name:"Betty", id:10},
    {src:faceTest, name:"Brian", id:11},
    {src:faceTest, name:"Josie", id:12},
    {src:faceTest, name:"Betty", id:13},
    {src:faceTest, name:"Brian", id:14},
    {src:faceTest, name:"Josie", id:15},
    {src:faceTest, name:"Betty", id:16},
    {src:faceTest, name:"Brian", id:17},
    {src:faceTest, name:"Josie", id:18},
    {src:faceTest, name:"Betty", id:19},
    {src:faceTest, name:"Brian", id:20},
    {src:faceTest, name:"Josie", id:21},
    {src:faceTest, name:"Betty", id:22},
    {src:faceTest, name:"Brian", id:23},
    {src:faceTest, name:"Josie", id:24},
  ]

  export default workers;